//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleccionesMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotosResultado
    {
        public int id_voto { get; set; }
        public Nullable<int> id_candidato { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_votante { get; set; }
    
        public virtual Candidato Candidato { get; set; }
        public virtual Votante Votante { get; set; }
    }
}
